version: "3.9"
services:
  db: 
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    expose: 
      - "5432"
    networks:
      - dotnet_net
    
  dotnet:
    build:
      context: ./backend
    environment:
      DB_HOST: "db"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - dotnet_net
    ports:
      - "80:80"
    depends_on:
      - db
      
networks:
  dotnet_net: