version: "3.9"

services:
  db: 
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    expose: 
      - "5432"
    networks:
      - dotnet_net

  dotnet:
    build:
      context: ./moleculeos-site-backend
    restart: always
    environment:
      DB_HOST: "db"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ASPNETCORE_ENVIRONMENT: "Production"
    networks:
      - dotnet_net
      - gateway
    expose:
      - "80:80"
    depends_on:
      - db

  nextjs:
    build:
      context: ./moleculeos-site-frontend
    command: yarn start
    restart: always
    expose:
      - "3000:3000"
    depends_on:
      - dotnet

  proxy:
    build:
      context: ./proxy
    restart: always
    environment:
      DOTNET_HOST: dotnet
      DOTNET_PORT: 80
      # BUG: Repair the 'host not found in upstream "nextjs:3000"'
      NEXTJS_HOST: nextjs
      NEXTJS_PORT: 3000
    depends_on:
      - dotnet
      - nextjs
    ports:
      - "80:80"
    networks:
      - gateway

networks:
  dotnet_net:
  gateway: