version: "3.9"
services:
  db: 
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ../postgres/data:/var/lib/postgresql/data
    expose: 
      - "5432"
    networks:
      - dotnet_net
    
  dotnet:
    build:
      context: .
    environment:
      DB_HOST: "db"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      JWT_KEY: ${JWT_KEY}
      JWT_EXPIRE_DAYS: ${JWT_EXPIRE_DAYS}
      JWT_ISSUER: ${JWT_ISSUER}
      
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - dotnet_net
    ports:
      - "80:80"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: ${DB_NAME}
    ports:
      - 8080:8080
    
      
networks:
  dotnet_net: